kydi/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include, re_path
import accounts
from rest_framework.authtoken import views
from accounts.serializers import CustomAuthToken

from django.views.generic.base import RedirectView

favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('register/complete', accounts.views.django_registration_complete, name='django_registration_complete'),
    path('activate/complete', accounts.views.django_activation_complete, name='django_registration_activation_complete'),
    path('api-token-auth/', CustomAuthToken.as_view()),
    re_path(r'^favicon\.ico$', favicon_view),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path, include
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.login_view, name='login'),
    path('logout/', views.logout_view, name="logout"),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('members/', views.members, name="members"),
    path('new-member/', views.new_member, name="new_member"),
    path('update-member/', views.update_member, name="update_member"),
    path('tulinaawe/', views.tulinaawe_view, name="tulinaawe"),
    path('tulinaawe/<slug>/', views.tulinaawe_detail, name="tulinaawe_detail"),
    path('welfare/', views.welfare_view, name="welfare"),
    path('loans/', views.loans_view, name="loans"),
    path('loans/<slug>', views.loan_detail, name="loan_detail"),
    path('loan/application/', views.loan_application_view, name="loan_application"),
    path('loan/application-detail/<slug>', views.loan_application_detail_view, name="loan_application_detail"),
    path('reports/', views.reports_view, name="reports"),
    path('expenses/', views.expenses_view, name="expenses"),
    path('expenses/<slug>/', views.expenses_detail, name="expenses_detail"),
    path('project-fee/', views.project_fee_view, name='project_fee'),
    path('vouchers/', views.vouchers_view, name='vouchers'),
    path('vouchers/<slug>/', views.vouchers_detail, name='vouchers_detail'),
    path('notes/', views.notes_view, name="notes"),

    path('<slug>/<slug2>-new-transaction/', views.member_new_transaction, name='member_new_transaction'),
    path('<slug>/<slug2>-transactions/', views.member_transactions, name="member_transactions"),

    path('<slug>/<slug2>-convert-savings/', views.convert_savings, name="convert_savings"),
    path('<slug>/<slug2>-pay-using-shares/', views.pay_using_shares, name="pay_using_shares"),

    path('new-transaction/', views.new_transaction, name="new_transaction"),
    path('all-transactions/', views.all_transactions, name="all_transactions"),
    path('transaction/<slug>/', views.transaction_view, name="transaction"),

    path('transaction/<slug>/detail/', views.transaction_detail, name="transaction_detail"),

    path('print/', views.print_view, name="print"),

    path('member/', views.member_info, name="member_info"),

    path('member-report/', views.member_report, name="member_report"),
    path('api/reports/', views.reports_api, name="reports_api"),
    path('api/member-report/', views.member_report_api, name="member_report_api"),

    path('api/member/', views.api_member_view, name='member-api'),
    path('api/transactions/', views.api_transaction_view, name='transactions-api'),
    path('api/loans/', views.api_loans_view, name='loans-api'),
    path('api/loans/<slug>/', views.api_loans_detail_view, name='loans-detail-api'),
    path('api/tulinaawe/', views.api_tulinaawe, name='tulinaawe-api'),
    path('api/reset-password/', views.api_reset_password, name='reset-password-api'),

    path('settings/', views.settings_view, name="settings"),
]

main/models.py
from django.db import models
from django.core.exceptions import ValidationError
import re


class FinancialYearManager(models.Manager):
	
	def fn_manager(self, start_date, end_date):
		return super().get_queryset().filter(date__range=(start_date, end_date))

class LoanFinancialYearManager(models.Manager):

	def fn_manager(self, start_date, end_date):
		return super().get_queryset().filter(date_created__range=(start_date, end_date))
	

class ExpensesFinancialYearManager(models.Manager):

	def fn_manager(self, start_date, end_date):
		return super().get_queryset().filter(date__range=(start_date, end_date))


class VoucherFinancialYearManager(models.Manager):

	def fn_manager(self, start_date, end_date):
		return super().get_queryset().filter(date__range=(start_date, end_date))
	

class ProjectFeeYearManager(models.Manager):

	def fn_manager(self, start_date, end_date):
		return super().get_queryset().filter(date__range=(start_date, end_date))


class Settings(models.Model):
	id = models.BigAutoField(primary_key=True)
	results_order = models.CharField(max_length=255, default="show last added")

	def __str__(self):
		return "%s"%self.id


class FinancialYear(models.Model):
	id = models.BigAutoField(primary_key=True)
	first_date = models.DateTimeField()
	second_date = models.DateTimeField()
	active = models.BooleanField(default=False)
	settings = models.ForeignKey(Settings, on_delete=models.CASCADE)

	def __str__(self):
		return "%s --> %s"%(self.first_date.date().strftime('%x') ,self.second_date.date().strftime('%x')) 


class Member(models.Model):

	#Choices

	gender_choices = [
		("male", "Male"),
		("female", "Female"),
	]

	marital_status_choices = [
		("single", "Single"),
		("married", "Married")
	]

	source_of_income_choices = [
		("salary", "Salary"),
		("business", "Business"),
		("pension", "Pension")
	]

	business_sector_choices = [
		("transport", "Transport"),
		("hospitality", "Hospitality"),
		("real_estate", "Real Estate"),
		("tourism", "Tourism"),
		("wholesale_retail", "Wholesale / Retail"),
		("financial_services", "Financial Services"),
		("health_care", "Health Care"),
		("manufacturing", "Manufacturing"),
		("education", "Education")
	]

	mode_of_remittance_choices = [
		("check_off", "Check Off"),
		("direct_deposit", "Direct Deposit"),
		("standing_order", "Standing Order"),
		("pay_bill_m_money", "Paybill (M-Money)")
	]



	#Basic Details
	id = models.BigAutoField(primary_key=True)
	code = models.CharField(max_length=255, unique=True)
	image = models.ImageField(blank=False, null=False)
	first_name = models.CharField(max_length=255)
	last_name = models.CharField(max_length=255)
	full_names = models.CharField(max_length=255, default="")
	contact = models.CharField(max_length=255)
	date_joined = models.DateTimeField()

	#Applicant Details
	email_address = models.EmailField(blank=True)
	residence = models.CharField(max_length=255, blank=True)
	town = models.CharField(max_length=255, blank=True)
	box_no = models.CharField(max_length=255, blank=True)
	town_code = models.CharField(max_length=255, blank=True)
	marital_status = models.CharField(max_length=255, choices=marital_status_choices)
	gender = models.CharField(max_length=255, choices=gender_choices)
	date_of_birth = models.DateTimeField(null=True, blank=True)
	identification_no = models.CharField(max_length=255, blank=True)
	source_of_income = models.CharField(max_length=255, blank=True, choices=source_of_income_choices)

	#Employment Details
	employer = models.CharField(max_length=255, blank=True)
	date_of_employment = models.DateTimeField(null=True, blank=True)
	employment_address = models.CharField(max_length=255, blank=True)
	position_in_employment = models.CharField(max_length=255, blank=True)
	staff_number = models.CharField(max_length=255, blank=True)

	#Business Details
	business_name = models.CharField(max_length=255, blank=True)
	business_address = models.CharField(max_length=255, blank=True)
	business_sector = models.CharField(max_length=255, blank=True, choices=business_sector_choices)
	business_sector_others = models.TextField(blank=True)
	business_location = models.CharField(max_length=255, blank=True)
	business_monthly_income = models.PositiveIntegerField(default=0, blank=True)

	#Remittance
	proposed_monthly_contribution = models.IntegerField(default=0, blank=True)
	effective_date = models.DateTimeField(null=True, blank=True)
	amount_in_words = models.CharField(max_length=255, blank=True)
	mode_of_remittance = models.CharField(max_length=255, blank=True, choices=mode_of_remittance_choices)

	#Totals
	shares = models.IntegerField(default=0)
	welfare = models.IntegerField(default=0)
	savings = models.IntegerField(default=0)
	withdraw = models.IntegerField(default=0)
	fines = models.IntegerField(default=0)
	other = models.IntegerField(default=0)
	project_fee = models.IntegerField(default=0)

	#Official Declaration
	data_captured_by = models.CharField(max_length=255, blank=True)
	data_date_capture = models.DateTimeField(null=True, blank=True)
	system_approval_by = models.CharField(max_length=255, blank=True)
	system_approval_date = models.DateField(null=True, blank=True)
	membership_approved_by = models.CharField(max_length=255, blank=True)
	membership_approval_date = models.DateTimeField(null=True, blank=True)
	admitted_by_1 = models.CharField(max_length=255, blank=True)
	admitted_by_1_date = models.DateTimeField(null=True, blank=True)
	admitted_by_2 = models.CharField(max_length=255, blank=True)
	admitted_by_2_date = models.DateTimeField(null=True, blank=True)

	class Meta:
		ordering = ["code"]

	@property
	def date_fields(self):
		return ['date_joined', 'date_of_birth', 'date_of_employment', 'effective_date', 'data_date_capture', 'system_approval_date', 'membership_approval_date', 'admitted_by_1_date', 'admitted_by_2_date']

	@property
	def name_snippet(self):
		if len(self.full_names) > 18:
			return "%s..."%(self.full_names[0:18])
		else:
			return self.full_names

	@property
	def full_name(self):
		return '%s %s'%(self.first_name, self.last_name)

	def clean(self):
		code_pattern = r'KYDI/\d+'
		contact_pattern = r'^\d{10}$'

		match_code = re.match(code_pattern, self.code)
		match_contact = re.match(contact_pattern, self.contact)

		if not match_code:
			raise ValidationError({'code': 'Code should be in the form KYDI/000'})

		if not match_contact:
			raise ValidationError({'contact': 'Invalid Contact'})
	        
	def save(self, *args, **kwargs):
		self.full_names = "%s %s"%(self.first_name, self.last_name)
		self.full_clean()
		return super().save(*args, **kwargs)

	def __str__(self):
		return "%s - %s"%(self.code, self.full_names)



class NomineesForDeposits(models.Model):
	id = models.BigAutoField(primary_key=True)
	name = models.CharField(max_length=255)
	id_no = models.CharField(max_length=255)
	relationship = models.CharField(max_length=255, default="")
	percentage = models.PositiveIntegerField(default=0)
	date_of_birth = models.DateTimeField()
	mobile_no = models.CharField(max_length=255)

	member = models.ForeignKey(Member, on_delete=models.CASCADE)

	def __str__(self): 
		return "%s --> %s"%(self.name, self.member)


class NomineesForGFE(models.Model):
	id = models.BigAutoField(primary_key=True)
	name = models.CharField(max_length=255)
	id_no = models.CharField(max_length=255)
	relationship = models.CharField(max_length=255, default="")
	percentage = models.PositiveIntegerField(default=0)
	date_of_birth = models.DateTimeField()
	mobile_no = models.CharField(max_length=255)

	member = models.ForeignKey(Member, on_delete=models.CASCADE)

	def __str__(self):
		return "%s -> %s"%(self.name, self.member)
	

class Transaction(models.Model):
	id = models.BigAutoField(primary_key=True)

	fines_choices = [
		("General Meeting", "General Meeting"),
		("Weekly Meeting", "Weekly Meeting"),
		("Late", "Late"),
		("Uniform", "Uniform"),
		("Minimum Savings", "Minimum Savings"),
	]

	date = models.DateTimeField()
	shares = models.IntegerField(default=0)
	welfare = models.IntegerField(default=0)
	savings = models.IntegerField(default=0)
	withdraw = models.IntegerField(default=0)
	project_fee = models.IntegerField(default=0)
	fines = models.IntegerField(default=0)
	fine_type = models.CharField(max_length=255, choices=fines_choices, null=True, blank=True)
	other = models.IntegerField(default=0, blank=True)
	notes = models.TextField(blank=True)
	member = models.ForeignKey(Member, on_delete=models.CASCADE)

	objects = FinancialYearManager()

	@property 
	def single_date(self):
		return self.date.date()

	@property
	def notes_snippet(self):
		return "%s..."%(self.notes[0:70])

	class Meta:
		ordering = ["-date", "member"]

	def __str__(self):
		return "%s: %s %s --> %s"%(self.member.code, self.member.first_name, self.member.last_name, self.date.date())


class TransactionType(models.Model):
	id = models.BigAutoField(primary_key=True)
	general = models.BooleanField(default=False)
	withdraw = models.BooleanField(default=False)
	fined = models.BooleanField(default=False)
	savings_to_shares = models.BooleanField(default=False)
	paid_fines = models.BooleanField(default=False)
	share_pay = models.BooleanField(default=False)

	transaction = models.OneToOneField(Transaction, on_delete=models.CASCADE)

	def __str__(self):
		return "%s %s --> %s"%(self.transaction.member.first_name, self.transaction.member.last_name, self.transaction.date.date())


class Tulinaawe(models.Model):
	id = models.BigAutoField(primary_key=True)
	date_due = models.DateTimeField(null=True)
	date_created = models.DateTimeField(auto_now_add=True, null=True, blank=True)
	title = models.CharField(max_length=255)
	description = models.TextField()
	status = models.BooleanField(default=True)
	total_amount_contributed = models.IntegerField(default=0)

	@property
	def title_snippet(self):
		if len(self.title) > 15:
			return "%s..."%(self.title[0:15])
		else:
			return "%s"%(self.title)

	@property
	def description_snippet(self):
		if len(self.description) > 40:

main/templates/main/member_new_transaction.html
{% extends 'index.html' %}
{% load static %}

{% block content %}
	<main id="main-body" class="h-full overflow-y-auto bg-bluish px-6">

		<div class="flex gap-4">
			<h2 class="mt-4 mb-3 text-xl font-semibold text-gray-600">Add Transaction</h2>

			<div class="mt-4 mb-3">

				<button id="general-transaction" class="active-t">
					General Transaction
				</button>

				<button id="other-transaction" class="ml-4 inactive-t">
					Other Transaction
				</button>
			</div>
		</div>

		<div class="w-full rounded-lg shadow-xs border bg-white py-2 px-4 mb-4">
			<input type="hidden" value="{{latest_date|date:"Y-m-d"}}" id="latest_date">
			<form method="POST" action="" id="transaction-add-form" class="form-control">

				{% csrf_token %}
				<input type="hidden" name="user-no-conflict" value="{{user}}">

				<div class="grid grid-cols-2 gap-8">
					<div>

						<div class="text-sm mt-4 pl-1">
							<p data="full-name" class="font-semibold">
								{{member.first_name}} {{member.last_name}}
							</p>
							<div class="w-48 h-48 mt-4">
								<img src="{{member.image.url}}" data="image">
							</div>
						</div>

						<div class="flex gap-4 mt-6">
							<input id="use-last-date" type="checkbox" style="appearance: checkbox; width: 16px; padding: 0; margin: 0; outline: none; border: none;">
							<label for="use-last-date" style="margin:0;">Use previous date</label>
						</div>

						<label for="id_date" style="margin-top: 1.4rem;">Date</label>
						{{form.date}}
						{{form.date.errors}}

						<div data-label="welfare">
							<label for="id_welfare">Welfare</label>
							{{form.welfare}}
							{{form.welfare.errors}}
						</div>

					</div>

					<div data-label="control-1" class="block">

						<label for="id_shares">Shares</label>
						{{form.shares}}
						{{form.shares.errors}}

						<label for="id_savings">Savings</label>
						{{form.savings}}
						{{form.savings.errors}}

						<label for="id_withdraw">Withdraw</label>
						{{form.withdraw}}
						{{form.withdraw.errors}}

						<label for="id_fines">Fines</label>
						{{form.fines}}
						{{form.fines.errors}}

						<label for="id_fine_type">Fine Type</label>
						{{form.fine_type}}
						{{form.fine_type.errors}}

					</div>

					<div data-label="control-2" class="hidden">
						<label for="id_fines">Other</label>
						{{form.other}}
						{{form.other.errors}}

						<label for="id_fine_type">Reason</label>
						{{form.other_reason}}
						{{form.other_reason.errors}}
					</div>
				</div>

				<div class="flex items-center justify-end">
					
					<input class="ml-0" type="submit" name="submit" value="Submit">
					
				</div>

			</form>
		</div>
	</main>
{% endblock %}

{% block scripts %}
	<script src="{% static 'custom_scripts/member_new_transaction.js' %}"></script>
{% endblock %}

main/templates/main/new_transaction.html
{% extends 'index.html' %}
{% load static %}

{% block link5 %}
active-link
{% endblock %}


{% block title %}
    <h2 class="border-b-2 border-indigo-500 ml-4 font-semibold text-gray-700">
        New Transaction
    </h2>
{% endblock %}

{% block content %}
	<main id="main-body" class="h-full overflow-y-auto bg-bluish px-6">

		<div class="flex gap-4">
			

			<div class="mt-4 mb-3">

				<button id="general-transaction" class="active-t">
					General Transaction
				</button>

				<button id="custom-transaction" class="ml-4 inactive-t">
					Custom Transaction
				</button>
			</div>
		</div>

		<div class="w-full rounded-lg shadow-xs border bg-white py-4 px-4  mb-4">

			<input type="hidden" value="{{latest_date|date:"Y-m-d"}}" id="latest_date">
           
            {% if edit %}
                <input type="hidden" value='{{edit_date|date:"Y-m-d"}}' name="edit">
            {% endif %}

			<form method="POST" action="{% url 'main:new_transaction' %}" id="transaction-add-form" class="form-control">
				{% csrf_token %}
				<input type="hidden" name="user-no-conflict" value="{{user}}">
                <input type="hidden" name="edit" value="{{edit}}">
                <input type="hidden" name="transaction-id" value="{{transaction_id}}">
				
				<div>
					
                    <div class="grid grid-cols-2 gap-8">

                        <div>

                            <label>
                                <span class="text-dark-heading">Member:</span><span class="text-red-500">*</span>
                            </label>
                            {{form.member}}
                            {{form.member.errors}}

                        </div>

                        <div>
                            <label>
                                <span>Date:</span><span class="text-red-500">*</span>
                                <span class="ml-2">
                                    <span>Use previous date</span>
                                    <input type="checkbox" id="use-last-date" class="custom-checkbox">
                                </span>
                            </label>
                            {{form.date}}
                            {{form.date.errors}}
                        </div>

                    </div>

                    <div id="general-transaction" class="block">

                        <div class="grid grid-cols-3 gap-8 mt-4">

                            <div>

                                <label>
                                    <span>Shares</span><span class="text-red-500">*</span>
                                </label>
                                {{form.shares}}
                                {{form.shares.errors}}

                            </div>

                            <div>
                                <label>
                                    <span>Welfare:</span><span class="text-red-500">*</span>
                                </label>
                                {{form.welfare}}
                                {{form.welfare.errors}}
                            </div>

                            <div>
                                <label>
                                    <span>Savings:</span><span class="text-red-500">*</span>
                                </label>
                                {{form.savings}}
                                {{form.savings.errors}}
                            </div>

                        </div>

                        <div class="grid grid-cols-3 gap-8 mt-4">

                            <div>

                                <label>
                                    <span>Withdraw:</span><span class="text-red-500">*</span>
                                </label>
                                {{form.withdraw}}
                                {{form.withdraw.errors}}
                            </div>

                            <div>
                                <label>
                                    <span>Fines:</span><span class="text-red-500">*</span>
                                </label>
                                {{form.fines}}
                                {{form.fines.errors}}
                            </div>

                            <div>
                                <label>
                                    <span>Project Fee:</span><span class="text-red-500">*</span>
                                </label>
                                {{form.project_fee}}
                                {{form.project_fee.errors}}
                            </div>

                        </div>

                    </div>

                    <div id="custom-transaction" class="hidden">

                        <label>
                            <span>Amount:</span><span class="text-red-500">*</span>
                        </label>
                        {{form.other}}
                        {{form.other.errors}}

                    </div>

				</div>

                <div class="grid grid-cols-2 gap-8">
                    <div class="mt-4 flex gap-8">

                        <div class="w-32 h-32 rounded-full border overflow-hidden">
                            {% if member_transaction or edit %}
                                <img src="{{member.image.url}}" data="image" alt="image" class="w-32 h-32">
                            {% else %}
                                <img src="#" alt="member" data="image" class="hidden w-32 h-32">
                            {% endif %}
                            
                        </div>

                        <div class="flex items-center">
                            <p data="full-name" class="text-gray-700">
                                {% if member_transaction or edit %}
                                    {{member.full_names}}
                                {% else %}
                                    Choose Member
                                {% endif %}
                            </p>
                        </div>

                    </div>

                    <div class="mt-4 notes">
                        <label>
                            <span>Notes:</span><span class="text-red-500">*</span>
                        </label>
                        
                        {{form.notes}}
                        {{form.notes.errors}}

                    </div>
                </div>

				<div class="flex items-center justify-end">
					<input type="submit" name="submit" value="Save" style="margin-top: 0; margin-bottom: 0;">
				</div>
				
			</form>

		</div>
	</main>
{% endblock %}

{% block scripts %}
	<script src="{% static 'custom_scripts/new_transaction.js' %}"></script>
{% endblock %}

main/templates/main/notes.html
{% extends 'index.html' %}
{% load static %}
{% load humanize %}

{% block title %}
    <h2 class="border-b-2 border-indigo-500 ml-4 font-semibold text-gray-700">
        Notes
    </h2>
{% endblock %}

{% block link10 %}
active-link
{% endblock %}


{% block content %}
	<main id="main-body" class="h-full overflow-y-auto bg-bluish px-6 pb-8 pt-4">

		<div class="grid grid-cols-3 gap-4">

			<div class="w-full rounded-lg shadow-xs border bg-white py-2 px-4 min-h-max">
				<form method="POST" action="" class="form-control">
					{% csrf_token %}
					{{form}}
					<input type="submit" name="submit" value="Save">
				</form>
			</div>

            {% for note in notes %}

                <div class="bg-white rounded-md max-h-72 overflow-y-auto relative group">

                    <div class="p-6">
                        {{note.content}}
                    </div>
                    

                    <div class="hidden justify-end gap-4 bg-gray-300 absolute bottom-0 w-full h-10 items-center group-hover:flex pr-4">
                        <a href="#">
                            <i data-feather="edit" class="text-gray-600"></i>
                        </a>
                        <a href="?id={{note.id}}&action=delete">
                            <i data-feather="trash-2" class="text-gray-600"></i>
                        </a>
                    </div>

                </div>

            {% endfor %}

		</div>
		
        

	</main>
{% endblock %}

{% block scripts %}
	<!-- <script src="{% static 'custom_scripts/notes.js' %}"></script> -->
{% endblock %}

main/templates/main/pay_using_shares.html
{% extends 'index.html' %}
{% load static %}
{% load humanize %}

{% block title %}
    <h2 class="border-b-2 border-indigo-500 ml-4 font-semibold text-gray-700">
        Pay Using Shares
    </h2>
{% endblock %}

{% block link2 %}
active-link
{% endblock %}

{% block content %}
	<main id="main-body" class="h-full overflow-y-auto bg-bluish px-6 pt-4">

		<div class="w-full rounded-lg shadow-xs border bg-white py-2 px-4">

			<form method="POST" action="" id="pay-using-shares-form" class="form-control">
				{% csrf_token %}
				<input type="hidden" name="user-no-conflict" value="{{user}}">
				
				<div>
					<div class="flex mt-4 pl-1">
						<div class="w-44 h-44">
							<img src="{{member.image.url}}" data="image" class="rounded-full">
						</div>
						<div class="ml-6">
							<p class="font-semibold">{{member.full_name}}</p>
							<p>{{member.code}}</p>
							<p>
								<span>Total Shares:</span>
								<span label="total-shares" data="{{member.shares}}">
									{{member.shares}}
								</span>
							</p>
						</div>
					</div>

					<div class="mt-4">
						<label for="id_date">Date</label>
						{{form.date}}
						{{form.date.errors}}

						<label for="id_fines">Shares</label>
						{{form.shares}}
						{{form.shares.errors}}

						<ul class="errorlist">
							<li></li>
						</ul>
					</div>

					<div class="hidden">
						{{form.savings}}
						{{form.withdraw}}
						{{form.welfare}}
                        {{form.fines}}
						{{form.fine_type}}
					</div>
				</div>

				<input type="submit" name="btnSubmit" value="Submit">
			</form>
		</div>
	</main>
{% endblock %}

{% block scripts %}
<script src="{% static 'custom_scripts/pay_using_shares.js' %}"></script>
{% endblock %}